"""
Diff a fresh Reddit scrape against the previous committed snapshot and build a
notification digest of the posts that are NEW this run. Also inspects the
scraper's own log to tell a genuinely-quiet day apart from a scrape that got
rate-limited/blocked (Reddit throttles datacenter IPs hard — see fetch_reddit.py).

Used by .github/workflows/reddit-notify.yml, but runnable locally:

    python reddit_digest.py \
        --baseline /tmp/reddit_baseline.json \
        --current  frontend/public/data/reddit_raw.json \
        --log      /tmp/scrape.log \
        --body-out reddit-issue-body.md

Outputs (for the workflow):
  - appends has_new / new_count / scrape_ok to $GITHUB_OUTPUT (if set)
  - writes the issue-body markdown to --body-out
  - prints a human summary
"""

import argparse
import json
import os
import re
from datetime import date
from pathlib import Path


def load(path: Path) -> list[dict]:
    if not path or not path.exists():
        return []
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        return data if isinstance(data, list) else []
    except (json.JSONDecodeError, OSError):
        return []


def scrape_health(log_path: Path) -> tuple[bool, int, int]:
    """Parse fetch_reddit.py's stdout. Returns (ok, total_raw_results, gave_up).

    A run where every query returned zero raw results (or every subreddit was
    given up on after retries) is almost certainly a block, not a quiet day."""
    if not log_path or not log_path.exists():
        return True, -1, 0  # no log to judge — don't cry wolf
    text = log_path.read_text(encoding="utf-8", errors="replace")
    raw = sum(int(n) for n in re.findall(r"->\s*(\d+)\s+raw results", text))
    gave_up = len(re.findall(r"Giving up on", text))
    # ok unless we truly got nothing back across the whole run
    ok = raw > 0
    return ok, raw, gave_up


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--baseline", required=True, help="pre-scrape snapshot of reddit_raw.json")
    ap.add_argument("--current", required=True, help="reddit_raw.json after the scrape")
    ap.add_argument("--log", default="", help="captured fetch_reddit.py stdout (health check)")
    ap.add_argument("--body-out", default="reddit-issue-body.md")
    args = ap.parse_args()

    baseline = load(Path(args.baseline))
    current = load(Path(args.current))
    base_ids = {r.get("id") for r in baseline}

    # New = present now, absent from the previous snapshot. Robust to the
    # scraper's re-sorting and its 90-day expiry pruning (both only reorder /
    # remove, never spuriously add).
    new_posts = [r for r in current if r.get("id") not in base_ids]
    new_posts.sort(
        key=lambda r: (r.get("relevance", {}).get("total", 0), r.get("created_utc") or ""),
        reverse=True,
    )

    ok, raw, gave_up = scrape_health(Path(args.log) if args.log else None)

    # Build the issue body.
    today = date.today().isoformat()
    lines = [f"## 🙋 {len(new_posts)} new volunteer-related Reddit post(s) — {today}", ""]
    if not ok:
        lines += [
            "> ⚠️ **Heads up:** the scrape returned **0 raw results** this run "
            f"({gave_up} subreddit(s) rate-limited to giving up). Reddit may be "
            "blocking the Actions runner IP, so this list could be incomplete.",
            "",
        ]
    if new_posts:
        lines += ["| Score | Subreddit | Post |", "|:-:|:--|:--|"]
        for r in new_posts:
            score = r.get("relevance", {}).get("total", 0)
            sub = f"r/{r.get('subreddit', '?')}"
            title = (r.get("title") or "(untitled)").replace("|", "\\|").strip()
            url = r.get("source_url") or ""
            lines.append(f"| {score} | {sub} | [{title}]({url}) |")
    else:
        lines.append("_No new posts since the last run._")
    lines += [
        "",
        "---",
        "_Auto-generated by `reddit-notify.yml` from `fetch_reddit.py` "
        f"(search.rss, no LLM). Raw results this run: {raw if raw >= 0 else 'n/a'}._",
    ]
    Path(args.body_out).write_text("\n".join(lines) + "\n", encoding="utf-8")

    # Surface outputs for the workflow.
    out = os.environ.get("GITHUB_OUTPUT")
    if out:
        with open(out, "a", encoding="utf-8") as f:
            f.write(f"has_new={'true' if new_posts else 'false'}\n")
            f.write(f"new_count={len(new_posts)}\n")
            f.write(f"scrape_ok={'true' if ok else 'false'}\n")

    print(f"New posts: {len(new_posts)} | scrape_ok={ok} (raw={raw}, gave_up={gave_up})")
    for r in new_posts[:10]:
        print(f"  [{r.get('relevance', {}).get('total', 0)}] r/{r.get('subreddit')} - "
              f"{(r.get('title') or '')[:70]}")


if __name__ == "__main__":
    main()
