// seo.js — the single source of truth for the words on a crawlable page.
//
// Every browse page needs the same handful of facts phrased four different
// ways: a <title>, a meta description, a visible <h1>, and a JSON-LD `name`.
// When those live in four places they drift, so each page type gets one
// function here that returns all of them, plus the prose block and FAQ.
//
// Why prose at all: cause and city pages used to be a meta description and a
// grid of cards, structurally identical across 39 URLs. Search engines read
// that as a thin template, and AI answer engines have nothing quotable to cite
// — they cite sentences, not card grids. Everything generated here is derived
// from real fields (counts, org names, cities, refresh dates), so it's specific
// per page and true by construction rather than padding.
//
// Pure module — no fs, no React — so it's importable from server pages and
// client components alike.

import { cityName } from './city'
import { tagMeta } from '../components/tagMeta'
import { cleanOrgName } from '../components/cleanText'

export const SITE_URL = 'https://www.good-deeds-dallas.org'
export const SITE_NAME = 'Good Deeds Dallas'
export const METRO = 'Dallas–Fort Worth'

// The card image generated by app/opengraph-image.jsx.
//
// It has to be named explicitly on every page that sets its own `openGraph`:
// Next replaces the parent `openGraph` object wholesale rather than merging
// into it, so a page that declares `openGraph: { title, description }` drops
// the inherited image and shares as a bare link. Every page below sets its own
// title and description, so every page must re-declare the image.
export const OG_IMAGE = {
  url: '/opengraph-image',
  width: 1200,
  height: 630,
  alt: `${SITE_NAME} — volunteer opportunities across ${METRO}`,
}

// Standard Next `metadata` for a page: canonical URL, OpenGraph and Twitter
// cards, all derived from one title/description pair so the three can't
// disagree with each other or with the page's <h1>.
export function pageMeta({ title, description, path }) {
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      title,
      description,
      url: path,
      type: 'website',
      siteName: SITE_NAME,
      images: [OG_IMAGE],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [OG_IMAGE.url],
    },
  }
}

// Human-readable name for each scrape source, for "gathered from …" copy.
// Keys match the `source` field on a listing record.
export const SOURCE_LABELS = {
  idealist: 'Idealist',
  curated: "the nonprofits' own websites",
  volunteermckinney: 'Volunteer McKinney',
  volunteergarland: 'Volunteer Garland',
  voly_dallas: 'Voly Dallas',
  dallasdoinggood: 'Dallas Doing Good',
}

// ── Small formatting helpers ─────────────────────────────────────────────────

export function plural(n, one, many = `${one}s`) {
  return n === 1 ? one : many
}

// ["a", "b", "c"] -> "a, b, and c"
export function joinList(items, conjunction = 'and') {
  const list = items.filter(Boolean)
  if (list.length === 0) return ''
  if (list.length === 1) return list[0]
  if (list.length === 2) return `${list[0]} ${conjunction} ${list[1]}`
  return `${list.slice(0, -1).join(', ')}, ${conjunction} ${list[list.length - 1]}`
}

export function formatDate(iso) {
  if (!iso) return null
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return null
  return d.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric', timeZone: 'UTC' })
}

// Most recent last_scraped across a set of listings.
export function lastRefreshed(listings) {
  const stamps = listings.map(o => o.last_scraped).filter(Boolean)
  if (!stamps.length) return null
  return stamps.reduce((max, t) => (t > max ? t : max))
}

// ── Aggregate facts about a set of listings ──────────────────────────────────

// The things every page's prose is built from: who's posting, where, and how
// fresh it is. One pass so a page with 700 listings doesn't walk them 5 times.
export function summarize(listings) {
  const orgs = new Map()
  const cities = new Map()
  const sources = new Map()
  const tags = new Map()
  let newest = null

  for (const o of listings) {
    // Cleaned, not raw: these names go into <title>, meta descriptions and
    // JSON-LD, where scraper noise ("… Posted By") would be visible to Google.
    const org = cleanOrgName(o.org_name)
    if (org) orgs.set(org, (orgs.get(org) || 0) + 1)
    const c = cityName(o)
    if (c) cities.set(c, (cities.get(c) || 0) + 1)
    if (o.source) sources.set(o.source, (sources.get(o.source) || 0) + 1)
    for (const t of o.unified_tags || []) tags.set(t, (tags.get(t) || 0) + 1)
    if (o.last_scraped && (!newest || o.last_scraped > newest)) newest = o.last_scraped
  }

  const rank = m => [...m.entries()].sort((a, b) => b[1] - a[1])

  return {
    total: listings.length,
    orgCount: orgs.size,
    topOrgs: rank(orgs).map(([name, count]) => ({ name, count })),
    topCities: rank(cities).map(([city, count]) => ({ city, count })),
    topTags: rank(tags).map(([tag, count]) => ({ tag, count })),
    sources: rank(sources).map(([source, count]) => ({ source, count })),
    newest,
  }
}

// "gathered from Idealist, Volunteer McKinney, and the nonprofits' own websites"
function sourceSentence(sources) {
  const labels = sources
    .map(({ source }) => SOURCE_LABELS[source])
    .filter(Boolean)
    .slice(0, 4)
  return labels.length ? `gathered from ${joinList(labels)}` : 'gathered from local volunteer portals and nonprofits'
}

// ── Cause pages ──────────────────────────────────────────────────────────────

export function tagPageCopy(tag, listings) {
  const label = tagMeta(tag).label
  const lower = label.toLowerCase()
  const s = summarize(listings)
  const refreshed = formatDate(s.newest)

  const title = `${label} volunteer opportunities in ${METRO}`
  const description =
    `${s.total} current ${lower} volunteer ${plural(s.total, 'opportunity', 'opportunities')} across ` +
    `the Dallas metro, updated weekly. Every listing links back to the original posting, where you sign up.`

  const cities = s.topCities.slice(0, 5).map(c => c.city)

  // Just the numbers. This used to also name the top cities, the sources, the
  // refresh date and the expiry policy — four sentences of throat-clearing above
  // a results grid that people came here to scan. Anyone who wants the detail
  // has the FAQ at the foot of the page and /about.
  // The <h1> directly above already names the cause, so the lead doesn't repeat
  // it — which also sidesteps the noun-plural tags reading badly as adjectives
  // ("animals volunteer roles", "seniors volunteer roles"). Same shape as the
  // home and city leads.
  const intro =
    `${s.total} open volunteer ${plural(s.total, 'role', 'roles')} from ${s.orgCount} ` +
    `${plural(s.orgCount, 'organization')} across ${METRO}.`

  const topOrg = s.topOrgs[0]
  const faq = [
    {
      q: `Where can I volunteer for ${lower} causes in Dallas?`,
      a:
        `There are ${s.total} open ${lower} volunteer ${plural(s.total, 'position', 'positions')} across ${METRO} right now, ` +
        `spread across ${s.orgCount} ${plural(s.orgCount, 'organization')}` +
        (topOrg ? `, with ${topOrg.name} currently posting the most (${topOrg.count})` : '') +
        `. ${cities.length ? `They're concentrated in ${joinList(cities.slice(0, 3))}.` : ''}`,
    },
    {
      q: `Do I need to sign up in advance to volunteer?`,
      a:
        `Almost always, yes. Every listing links back to where it was posted — the organization's own site, or a ` +
        `portal like Idealist or Voly — and you register there. Some roles ask for an orientation or a ` +
        `background check first, especially those working with children or in healthcare settings. Good Deeds ` +
        `Dallas doesn't take signups itself; it points you at the source.`,
    },
    {
      q: `How current are these ${lower} listings?`,
      a:
        `Every source is rechecked weekly, and one-time events are removed the day after they happen, so what ` +
        `you see is what was live as of ${refreshed || 'the most recent refresh'}. Listings also pass a quality ` +
        `check that removes duplicates, paid positions, and donation drives that aren't actually volunteer roles.`,
    },
  ]

  return { label, title, description, h1: title, intro, faq, summary: s }
}

// ── City pages ───────────────────────────────────────────────────────────────

export function cityPageCopy(city, listings) {
  const s = summarize(listings)
  const refreshed = formatDate(s.newest)

  const title = `Volunteer opportunities in ${city}, TX`
  const description =
    `${s.total} current volunteer ${plural(s.total, 'opportunity', 'opportunities')} in ${city}, Texas, ` +
    `updated weekly. Every listing links back to the original posting, where you sign up.`

  const causes = s.topTags.slice(0, 5).map(t => tagMeta(t.tag).label.toLowerCase())

  // Numbers only — see the note on tagPageCopy above.
  const intro =
    `${s.total} open volunteer ${plural(s.total, 'role', 'roles')} from ${s.orgCount} ` +
    `${plural(s.orgCount, 'organization')} in ${city}, Texas.`

  const topOrg = s.topOrgs[0]
  const faq = [
    {
      q: `Where can I volunteer in ${city}, TX?`,
      a:
        `${s.orgCount} ${plural(s.orgCount, 'organization')} ${plural(s.orgCount, 'is', 'are')} currently ` +
        `looking for volunteers in ${city}` +
        (topOrg ? `, including ${joinList(s.topOrgs.slice(0, 3).map(o => o.name))}` : '') +
        `. ${causes.length ? `The largest categories are ${joinList(causes.slice(0, 3))}.` : ''}`,
    },
    {
      q: `Are there weekend or one-time volunteer opportunities in ${city}?`,
      a:
        `Yes — the index mixes ongoing roles with one-time events and shifts. Each listing shows its schedule ` +
        `where the organization published one, and dated events are removed automatically once they've passed, ` +
        `so nothing here has already happened.`,
    },
    {
      q: `Do I need experience to volunteer in ${city}?`,
      a:
        `Most roles need none. Listings note any requirement the organization stated — a minimum age, a ` +
        `background check, an orientation session, or a specific skill. Anything with a real prerequisite says so ` +
        `on its own page at the organization's site.`,
    },
  ]

  return { title, description, h1: title, intro, faq, summary: s }
}

// ── Organization pages ───────────────────────────────────────────────────────

export function orgPageCopy(org) {
  const listings = org.entries || []
  const s = summarize(listings)
  const refreshed = formatDate(s.newest)

  const cities = s.topCities.map(c => c.city)
  const where = cities.length ? cities.slice(0, 3).join(', ') : METRO
  const causes = s.topTags.slice(0, 4).map(t => tagMeta(t.tag).label.toLowerCase())

  const title = `Volunteer with ${org.name}${cities.length === 1 ? ` in ${cities[0]}` : ''}`
  const description =
    `${s.total} volunteer ${plural(s.total, 'opportunity', 'opportunities')} with ${org.name} in ${where}. ` +
    `Current openings, causes, and where to sign up.`

  const intro = [
    `${org.name} currently has ${s.total} volunteer ${plural(s.total, 'opportunity', 'opportunities')} open ` +
      `in ${joinList(cities.slice(0, 4)) || METRO}.`,
    causes.length
      ? `Their work covers ${joinList(causes)}.`
      : '',
    `Listings ${sourceSentence(s.sources)}${refreshed ? ` and last checked ${refreshed}` : ''}. ` +
      `Signing up happens at the source — use the link on any listing below.`,
  ].filter(Boolean).join(' ')

  const faq = [
    {
      q: `How do I volunteer with ${org.name}?`,
      a:
        `${org.name} has ${s.total} open volunteer ${plural(s.total, 'role', 'roles')} listed. Pick the one you ` +
        `want below and follow its link back to the original posting to register — Good Deeds Dallas indexes the ` +
        `openings but doesn't handle signups itself.`,
    },
    {
      q: `Where is ${org.name} located?`,
      a: cities.length
        ? `Their listed volunteer opportunities are in ${joinList(cities.slice(0, 6))}, Texas.`
        : `Their volunteer opportunities are across the ${METRO} metroplex.`,
    },
  ]

  return { title, description, h1: `Volunteer with ${org.name}`, intro, faq, summary: s }
}

// ── JSON-LD builders ─────────────────────────────────────────────────────────

export function breadcrumbLd(trail) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: trail.map(({ name, path }, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name,
      item: `${SITE_URL}${path}`,
    })),
  }
}

export function faqLd(faq) {
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faq.map(({ q, a }) => ({
      '@type': 'Question',
      name: q,
      acceptedAnswer: { '@type': 'Answer', text: a.replace(/\s+/g, ' ').trim() },
    })),
  }
}

// ItemList of opportunities. Capped because the point is topical signal, not a
// full data dump — the visible page carries the rest.
export function itemListLd(name, listings, limit = 50) {
  return {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    name,
    numberOfItems: listings.length,
    itemListElement: listings.slice(0, limit).map((o, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: o.opportunity_title,
      url: o.source_url,
    })),
  }
}
